### ISSUE TITLE
The sudo_version fact crashes when sudo is not installed

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/puppet-sudo#28]
```
Info: Loading facts
Error: Could not retrieve local facts: undefined method `match' for nil:NilClass
Error: Failed to apply catalog: Could not retrieve local facts: undefined method `match' for nil:NilClass
```

**Comment by mcanevet** [comment]
@ckaenzig maybe it time to finish the transition to saz-sudo even if it is not "approved" (but non is) as we already have an API compatilibity AFAIK

**Comment by mcanevet** [comment]
Fixed by https://github.com/camptocamp/puppet-sudo/commit/c51331279b51e958fdae2ef78924ba0bd6047faf
